
baseURL = "https://memwey.github.io/"
languageCode = "zh-hans"
title = "Mem.Wey's Github Pages"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true
rssLimit = 10 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-138801420-1"
disqusShortname = "memwey"

publishDir = "docs"

[author]
  name = "Mem Wey"

[blackfriday]
  hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "This may the last time we can meet."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/memwey/memwey.github.io/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/memwey"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/Mem_Wey"
 
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/memwey"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
